mkdir -p build/qpu
mkdir -p build/util
mkdir -p build/comm
mkdir -p build/mcu
mkdir -p build/blob
mkdir -p build/camera
mkdir -p build/vcsm
mkdir -p build/hash

/usr/bin/gcc -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -Wall -std=gnu17 -O1 -o build/qpu/mailbox.c.o -c source/qpu/mailbox.c
/usr/bin/gcc -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -Wall -std=gnu17 -O1 -o build/qpu/qpu_base.c.o -c source/qpu/qpu_base.c
/usr/bin/gcc -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -Wall -std=gnu17 -O1 -o build/qpu/qpu_program.c.o -c source/qpu/qpu_program.c
/usr/bin/gcc -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -Wall -std=gnu17 -O1 -o build/qpu/qpu_info.c.o -c source/qpu/qpu_info.c
/usr/bin/gcc -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -Wall -std=gnu17 -O1 -o build/util/fbUtil.c.o -c source/util/fbUtil.c
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/util/image.cpp.o -c ../shared/util/image.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/comm.cpp.o -c source/comm/comm.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/protocol_stream.cpp.o -c ../shared/comm/protocol_stream.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/server.cpp.o -c source/comm/server.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/uart.cpp.o -c source/comm/uart.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/timesync.cpp.o -c source/comm/timesync.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/wireless.cpp.o -c source/comm/wireless.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/comm/firmware.cpp.o -c source/comm/firmware.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/mcu/mcu.cpp.o -c source/mcu/mcu.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/mcu/stm32_bootloader.cpp.o -c source/mcu/stm32_bootloader.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/blob/detection.cpp.o -c source/blob/detection.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/blob/refinement.cpp.o -c ../shared/blob/refinement.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/blob/blob.cpp.o -c ../shared/blob/blob.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/hash/crc32.cpp.o -c ../shared/hash/crc32.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/hash/sha256.cpp.o -c ../shared/hash/sha256.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/main.cpp.o -c source/main.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/camera/gcs_v4l2.cpp.o -c source/camera/gcs_v4l2.cpp
/usr/bin/g++ -DARMV7 -Ienv/include -I../shared -Idependencies -Isource -g -rdynamic -fno-omit-frame-pointer -std=c++20 -Wall -Wno-sign-compare -Wno-pointer-arith -Wno-format-overflow -Wno-unused-label -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format -O1 -o build/vcsm/vcsm.cpp.o -c source/vcsm/vcsm.cpp

rm -r build